name: Github Action Activity
on:
# Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches:
      - master
jobs:
  build:
  # The type of runner that the job will run on 
    runs-on: ubuntu-latest
    
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it  
      - uses: actions/checkout@master
      # First step of the job will zip the package file to be deployed
      - name: Zip the package
        run: |
        # Locate the path of your packages and install the zip command
          cd packages
          sudo apt-get install -y zip
        # Zip the lansangan-github-action package file    
          zip -qr ../lansangan-github-action.zip lansangan-github-action/*

      # Upload the zip file as artifacts so that it can be used on the other jobs providing the artifact name and path      
      - uses: actions/upload-artifact@master
        with:
          name: my-artifact
          path: lansangan-github-action.zip
      # Second step of the job will deploy the package in Martini Server using REST API  
      - name: Deploy to the server
        run: |
         # Install jq command to transform JSON data into a more readable format 
          sudo apt-get install -y jq
         # Create a variable name that will acquire your access token from the Martini Server
          echo "[INFO] Retrieving Access Token...."   
          access_token=$(curl -X POST ${{secrets.SERVER_TORO}}/oauth/token -H 'Accept:application/json' -H 'Content-Type:application/x-www-form-urlencoded' -d 'grant_type=password&username=${{secrets.USERNM}}&password=${{secrets.PASSW}}&client_id=TOROMartini&client_secret=TOROMartini' | jq -r .access_token)
         # This command will upload your package in Martini Server using REST API  
          echo "[INFO] Uploading Martini Package...."
          curl -X POST "${{secrets.SERVER_TORO}}/esbapi/packages/upload?stateOnCreate=STARTED" -H  "accept:application/json" -H  "Content-Type:multipart/form-data" -F "file=@lansangan-github-action.zip;type=application/x-zip-compressed" -H "Authorization:Bearer $access_token"