# Specifying the stages which a keyword that defines certain stages of job
stages:
   - zipping
   - deploy
 
# This job is responsible for zipping the package to be deployed
zipping-the-package:
     stage: zipping
     script:
         # Install the zip command
         - cd packages
         - apt-get update -y
         - apt-get -y install zip
         # Zip the brmenesesPackage package
         - zip -r brmenesesPackage.zip brmenesesPackage/
     # Set the path of the zip file as artifact
     artifacts:
           paths:
              - packages/brmenesesPackage.zip
              
# Deploy the package to Martini server using API
deploy-the-package:
     stage: deploy
     script:
         # Install the jq command which is a useful tool to extract data from Json document
         - apt-get update -y
         - apt-get -y install jq
         # Retrieve the access token
         - ToroTokens=$(curl -X POST $TokenURL -H 'Accept:application/json' -H 'Content-Type:application/x-www-form-urlencoded' -d "grant_type=password&username="$ToroUSR"&password="$ToroPWD"&client_id=TOROMartini&client_secret=TOROMartini" | jq -r .access_token)
         # Upload the Package to Martini server
         - curl -X POST "$ToroSVR/esbapi/packages/upload?stateOnCreate=STARTED&replaceExisting=true" -H  "accept:application/json" -H  "Content-Type:multipart/form-data" -F "file=@packages/brmenesesPackage.zip;type=application/x-zip-compressed" -H "Authorization:Bearer $ToroTokens"